### ISSUE TITLE
Test "MustacheTest#test_utf8:" fails on non-utf8 systems.

### ISSUE THREAD

**Issue by voxik** [mustache/mustache#208]
This pass (and is default on plenty of systems):

```
$ LANG=en_US.utf8 ruby -Ilib test/mustache_test.rb - -n /test_utf8/
Run options: -n /test_utf8/ --seed 44212

# Running:

.

Finished in 0.001449s, 690.1892 runs/s, 690.1892 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

while this fails:

```
$ LANG=C ruby -Ilib test/mustache_test.rb - -n /test_utf8/
Run options: -n /test_utf8/ --seed 65369

# Running:

E

Finished in 0.001890s, 529.2128 runs/s, 0.0000 assertions/s.

  1) Error:
MustacheTest#test_utf8:
ArgumentError: invalid byte sequence in US-ASCII
    /builddir/build/BUILD/rubygem-mustache-1.0.2/usr/share/gems/gems/mustache-1.0.2/lib/mustache/context.rb:31:in `gsub'
    /builddir/build/BUILD/rubygem-mustache-1.0.2/usr/share/gems/gems/mustache-1.0.2/lib/mustache/context.rb:31:in `partial'
    /builddir/build/BUILD/rubygem-mustache-1.0.2/usr/share/gems/gems/mustache-1.0.2/lib/mustache/template.rb:47:in `render'
    /builddir/build/BUILD/rubygem-mustache-1.0.2/usr/share/gems/gems/mustache-1.0.2/lib/mustache/template.rb:43:in `render'
    /builddir/build/BUILD/rubygem-mustache-1.0.2/usr/share/gems/gems/mustache-1.0.2/lib/mustache.rb:119:in `render'
    test/mustache_test.rb:589:in `test_utf8'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

Please note the difference in LANG environment variable.

**Comment by voxik** [comment]
Still issue with Mustache 1.1.1.
