### ISSUE TITLE
Squared brackets not supported 

### ISSUE THREAD

**Issue by eni9889** [mustache/mustache#251]
I am trying the following template:

```
Mustache.render('{{ user[first_name] }} from {{ country }}', JSON.parse('{"user[first_name]" : "Michael"}'))
```

But am getting an exception about using the [] in my key.

When I try it on http://tryhandlebarsjs.com/ with the mustache engine I see no issues
![image](https://user-images.githubusercontent.com/360222/55257582-9216ae80-521d-11e9-9a3f-02bdc55f5d09.png)

Thanks for the help

**Comment by locks** [comment]
For reference:

```
irb(main):002:0> require 'json'; require 'mustache'
=> false
irb(main):003:0> Mustache.render('{{ user[first_name] }} from {{ country }}', JSON.parse('{"user[first_name]" : "Michael"}'))
Traceback (most recent call last):
       13: from /usr/local/opt/asdf/installs/ruby/2.6.2/bin/irb:23:in `<main>'
       12: from /usr/local/opt/asdf/installs/ruby/2.6.2/bin/irb:23:in `load'
       11: from /usr/local/Cellar/asdf/0.7.0/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       10: from (irb):3
        9: from /usr/local/Cellar/asdf/0.7.0/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mustache-1.1.0/lib/mustache.rb:88:in `render'
        8: from /usr/local/Cellar/asdf/0.7.0/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mustache-1.1.0/lib/mustache.rb:129:in `render'
        7: from /usr/local/Cellar/asdf/0.7.0/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mustache-1.1.0/lib/mustache/template.rb:36:in `render'
        6: from /usr/local/Cellar/asdf/0.7.0/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mustache-1.1.0/lib/mustache/template.rb:50:in `compile'
        5: from /usr/local/Cellar/asdf/0.7.0/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mustache-1.1.0/lib/mustache/template.rb:59:in `tokens'
        4: from /usr/local/Cellar/asdf/0.7.0/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mustache-1.1.0/lib/mustache/parser.rb:134:in `compile'
        3: from /usr/local/Cellar/asdf/0.7.0/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mustache-1.1.0/lib/mustache/parser.rb:212:in `scan_tags'
        2: from /usr/local/Cellar/asdf/0.7.0/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mustache-1.1.0/lib/mustache/parser.rb:164:in `find_closing_tag'
        1: from /usr/local/Cellar/asdf/0.7.0/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/mustache-1.1.0/lib/mustache/parser.rb:286:in `error'
Mustache::Parser::SyntaxError (Unclosed tag)
  Line 1
    {{ user[first_name] }} from {{ country }}
          ^
```
